
module.exports = {
  'brandBase': '#fbbe02',
  'actionElementBase': '#3e8529',
  'actionElementActive': '#67D04A',
  'mutedElementBase': '#ffffff',
  'mutedElementActive': '#f7f7f7',
  'textLight': '#ffffff',
  'textBase': '#4C4E54',
  'textGray': '#bbbbbe',
  'textGrayDark': '#22232e',
  'textHeader': '#ffffff',
  'textFooter': '#1d1f29',
  'borderBase': '#abadb1',
  'borderLight': '#e9eaeb',
  'backgroundLight': '#ffffff',
  'backgroundBase': '#f7f7f7',
  'backgroundDark': '#393c4c',
  'backgroundGray': '#bbbbbe',
  'backgroundError': '#c30000',
  'backgroundHeader': '#393c4c',
  'backgroundFooter': '#f7f7f7',
  'breadCrumbsBase': '#9199a8',
  'breadCrumbsActive': '#367a25',
  'errorBase': '#c30000',
  'container-width': '1400px',
  'narrow-container-width': '800px',
  'wide-container-width': '1600px',
  'verificationTitle': 'The Hays App',
  'footerText': 'The Hays App'
};
